language: R
sudo: false

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

repos:
  cran: http://cran.rstudio.com
  rforge: http://R-Forge.R-project.org


script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
